version: '3'
services:
  Lobby Service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=LobbyService
    volumes:
      - game-data-volume:/app/data
    environment:
      NODE_ENV: production
    ports:
      - ${PORT}:8080
    entrypoint:
      - /sbin/tini
      - --
    command: ["node", "index.js"]
    

  Game Service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=GameService
    volumes:
      - game-data-volume:/app/data
    environment:
      NODE_ENV: production
    ports:
      - "${PORT}:8080"
    entrypoint: ["/sbin/tini", "--"]
    command: ["node", "index.js"]

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

volumes:
  game-data-volume: