version: '3'
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - game-data-volume:/app/data
    environment:
      NODE_ENV: production
      SERVICE: GatewayService
    ports:
      - 3333:8080
    entrypoint:
      - /sbin/tini
      - --
    command: ["node", "index.js"]

  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - game-data-volume:/app/data
    environment:
      NODE_ENV: production
      SERVICE: MonitorService
    ports:
      - 4444:8080
    entrypoint:
      - /sbin/tini
      - --
    command: ["node", "index.js"]

  lobby:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - game-data-volume:/app/data
    environment:
      NODE_ENV: production
      SERVICE: LobbyService
    ports:
      - 7777:8080
    entrypoint:
      - /sbin/tini
      - --
    command: ["node", "index.js"]

  game:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - game-data-volume:/app/data
    environment:
      NODE_ENV: production
      SERVICE: GameService
    ports:
      - "8888:8080"
    entrypoint: ["/sbin/tini", "--"]
    command: ["node", "index.js"]

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

volumes:
  game-data-volume: