version: '3'
services:
  matchmaking:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=Matchmaking
    volumes:
      - game-data-volume:/app/data
    environment:
      NODE_ENV: development
      EXT_IP: 172.16.0.2
      EXT_PORT: 8080
    ports:
      - 8080:8080
    entrypoint:
      - /sbin/tini
      - --
    command: ["node", "matchmaking.js"]
    networks:
      network:
        ipv4_address: 172.16.0.2

  gameserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=Gameserver
    volumes:
      - game-data-volume:/app/data
    environment:
      NODE_ENV: development
      EXT_IP: 172.16.0.3
      EXT_PORT: 7777
    ports:
      - "7777:8080"
    entrypoint:
      - /sbin/tini
      - --
    command: ["node", "gameserver.js"]
    networks:
      network:
        ipv4_address: 172.16.0.3

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

volumes:
  game-data-volume: